### ISSUE TITLE
Please complete the document.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/FOSS-Collab-Hub#1]
The document currently at this stage is incomplete. Kindly someone pick this up and complete with some relevant information. Please let me know what information can be added?

**Comment by Dhairya1Gupta** [comment]
Issue complete

**Comment by Rajansharma44** [comment]
i have eager to learn new things or connect with peoples.

**Comment by setco-website** [comment]
Hi Praveen, I have been in your Live Stream so I know what to write. I am planning to add a couple of information like you showed us a Video and also a practical guide to Git and GitHub.

**Comment by praveenscience** [comment]
Hey @setco-website, you're up for it, go ahead and show what you can do! 😊
